%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clearvars -global
clear_persistent_variables(fileparts(which('dynare')), false)
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info
options_ = [];
M_.fname = 'EC424_NKD_developing';
M_.dynare_version = '6.2';
oo_.dynare_version = '6.2';
options_.dynare_version = '6.2';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'eps_a'};
M_.exo_names_tex(1) = {'eps\_a'};
M_.exo_names_long(1) = {'eps_a'};
M_.exo_names(2) = {'eps_g'};
M_.exo_names_tex(2) = {'eps\_g'};
M_.exo_names_long(2) = {'eps_g'};
M_.exo_names(3) = {'eps_u'};
M_.exo_names_tex(3) = {'eps\_u'};
M_.exo_names_long(3) = {'eps_u'};
M_.exo_names(4) = {'eps_v'};
M_.exo_names_tex(4) = {'eps\_v'};
M_.exo_names_long(4) = {'eps_v'};
M_.exo_names(5) = {'eps_e'};
M_.exo_names_tex(5) = {'eps\_e'};
M_.exo_names_long(5) = {'eps_e'};
M_.endo_names = cell(15,1);
M_.endo_names_tex = cell(15,1);
M_.endo_names_long = cell(15,1);
M_.endo_names(1) = {'y'};
M_.endo_names_tex(1) = {'y'};
M_.endo_names_long(1) = {'y'};
M_.endo_names(2) = {'ii'};
M_.endo_names_tex(2) = {'ii'};
M_.endo_names_long(2) = {'ii'};
M_.endo_names(3) = {'rn'};
M_.endo_names_tex(3) = {'rn'};
M_.endo_names_long(3) = {'rn'};
M_.endo_names(4) = {'pie'};
M_.endo_names_tex(4) = {'pie'};
M_.endo_names_long(4) = {'pie'};
M_.endo_names(5) = {'a'};
M_.endo_names_tex(5) = {'a'};
M_.endo_names_long(5) = {'a'};
M_.endo_names(6) = {'g'};
M_.endo_names_tex(6) = {'g'};
M_.endo_names_long(6) = {'g'};
M_.endo_names(7) = {'u'};
M_.endo_names_tex(7) = {'u'};
M_.endo_names_long(7) = {'u'};
M_.endo_names(8) = {'v'};
M_.endo_names_tex(8) = {'v'};
M_.endo_names_long(8) = {'v'};
M_.endo_names(9) = {'e'};
M_.endo_names_tex(9) = {'e'};
M_.endo_names_long(9) = {'e'};
M_.endo_names(10) = {'ex'};
M_.endo_names_tex(10) = {'ex'};
M_.endo_names_long(10) = {'ex'};
M_.endo_names(11) = {'m'};
M_.endo_names_tex(11) = {'m'};
M_.endo_names_long(11) = {'m'};
M_.endo_names(12) = {'AUX_ENDO_LAG_3_1'};
M_.endo_names_tex(12) = {'AUX\_ENDO\_LAG\_3\_1'};
M_.endo_names_long(12) = {'AUX_ENDO_LAG_3_1'};
M_.endo_names(13) = {'AUX_ENDO_LAG_3_2'};
M_.endo_names_tex(13) = {'AUX\_ENDO\_LAG\_3\_2'};
M_.endo_names_long(13) = {'AUX_ENDO_LAG_3_2'};
M_.endo_names(14) = {'AUX_ENDO_LAG_0_1'};
M_.endo_names_tex(14) = {'AUX\_ENDO\_LAG\_0\_1'};
M_.endo_names_long(14) = {'AUX_ENDO_LAG_0_1'};
M_.endo_names(15) = {'AUX_ENDO_LAG_0_2'};
M_.endo_names_tex(15) = {'AUX\_ENDO\_LAG\_0\_2'};
M_.endo_names_long(15) = {'AUX_ENDO_LAG_0_2'};
M_.endo_partitions = struct();
M_.param_names = cell(23,1);
M_.param_names_tex = cell(23,1);
M_.param_names_long = cell(23,1);
M_.param_names(1) = {'beta'};
M_.param_names_tex(1) = {'beta'};
M_.param_names_long(1) = {'beta'};
M_.param_names(2) = {'sigma'};
M_.param_names_tex(2) = {'sigma'};
M_.param_names_long(2) = {'sigma'};
M_.param_names(3) = {'phi'};
M_.param_names_tex(3) = {'phi'};
M_.param_names_long(3) = {'phi'};
M_.param_names(4) = {'epsilon'};
M_.param_names_tex(4) = {'epsilon'};
M_.param_names_long(4) = {'epsilon'};
M_.param_names(5) = {'theta'};
M_.param_names_tex(5) = {'theta'};
M_.param_names_long(5) = {'theta'};
M_.param_names(6) = {'alpha'};
M_.param_names_tex(6) = {'alpha'};
M_.param_names_long(6) = {'alpha'};
M_.param_names(7) = {'PSI_yan'};
M_.param_names_tex(7) = {'PSI\_yan'};
M_.param_names_long(7) = {'PSI_yan'};
M_.param_names(8) = {'THETA'};
M_.param_names_tex(8) = {'THETA'};
M_.param_names_long(8) = {'THETA'};
M_.param_names(9) = {'lambda'};
M_.param_names_tex(9) = {'lambda'};
M_.param_names_long(9) = {'lambda'};
M_.param_names(10) = {'kappa'};
M_.param_names_tex(10) = {'kappa'};
M_.param_names_long(10) = {'kappa'};
M_.param_names(11) = {'rho'};
M_.param_names_tex(11) = {'rho'};
M_.param_names_long(11) = {'rho'};
M_.param_names(12) = {'rho_a'};
M_.param_names_tex(12) = {'rho\_a'};
M_.param_names_long(12) = {'rho_a'};
M_.param_names(13) = {'rho_g'};
M_.param_names_tex(13) = {'rho\_g'};
M_.param_names_long(13) = {'rho_g'};
M_.param_names(14) = {'rho_u'};
M_.param_names_tex(14) = {'rho\_u'};
M_.param_names_long(14) = {'rho_u'};
M_.param_names(15) = {'rho_v'};
M_.param_names_tex(15) = {'rho\_v'};
M_.param_names_long(15) = {'rho_v'};
M_.param_names(16) = {'rho_e'};
M_.param_names_tex(16) = {'rho\_e'};
M_.param_names_long(16) = {'rho_e'};
M_.param_names(17) = {'rho_m'};
M_.param_names_tex(17) = {'rho\_m'};
M_.param_names_long(17) = {'rho_m'};
M_.param_names(18) = {'OMEGA'};
M_.param_names_tex(18) = {'OMEGA'};
M_.param_names_long(18) = {'OMEGA'};
M_.param_names(19) = {'TAU'};
M_.param_names_tex(19) = {'TAU'};
M_.param_names_long(19) = {'TAU'};
M_.param_names(20) = {'MU'};
M_.param_names_tex(20) = {'MU'};
M_.param_names_long(20) = {'MU'};
M_.param_names(21) = {'IOTA'};
M_.param_names_tex(21) = {'IOTA'};
M_.param_names_long(21) = {'IOTA'};
M_.param_names(22) = {'phi_pie'};
M_.param_names_tex(22) = {'phi\_pie'};
M_.param_names_long(22) = {'phi_pie'};
M_.param_names(23) = {'phi_y'};
M_.param_names_tex(23) = {'phi\_y'};
M_.param_names_long(23) = {'phi_y'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 15;
M_.param_nbr = 23;
M_.orig_endo_nbr = 11;
M_.aux_vars(1).endo_index = 12;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 4;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'pie(-1)';
M_.aux_vars(2).endo_index = 13;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 4;
M_.aux_vars(2).orig_lead_lag = -2;
M_.aux_vars(2).orig_expr = 'AUX_ENDO_LAG_3_1(-1)';
M_.aux_vars(3).endo_index = 14;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 1;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(3).orig_expr = 'y(-1)';
M_.aux_vars(4).endo_index = 15;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 1;
M_.aux_vars(4).orig_lead_lag = -2;
M_.aux_vars(4).orig_expr = 'AUX_ENDO_LAG_0_1(-1)';
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.learnt_shocks = [];
M_.learnt_endval = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
M_.matched_irfs = {};
M_.matched_irfs_weights = {};
options_.linear = true;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
options_.ramsey_policy = false;
options_.discretionary_policy = false;
M_.nonzero_hessian_eqs = [];
M_.hessian_eq_zero = isempty(M_.nonzero_hessian_eqs);
M_.eq_nbr = 15;
M_.ramsey_orig_eq_nbr = 0;
M_.ramsey_orig_endo_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 3;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 3;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 3;
M_.lead_lag_incidence = [
 1 12 27;
 0 13 0;
 0 14 0;
 2 15 28;
 3 16 29;
 4 17 0;
 5 18 0;
 6 19 0;
 7 20 0;
 0 21 0;
 0 22 0;
 8 23 0;
 9 24 0;
 10 25 0;
 11 26 0;]';
M_.nstatic = 4;
M_.nfwrd   = 0;
M_.npred   = 8;
M_.nboth   = 3;
M_.nsfwrd   = 3;
M_.nspred   = 11;
M_.ndynamic   = 11;
M_.dynamic_tmp_nbr = [0; 0; 0; 0; ];
M_.equations_tags = {
  1 , 'name' , 'y' ;
  2 , 'name' , 'rn' ;
  3 , 'name' , 'ii' ;
  4 , 'name' , 'm' ;
  5 , 'name' , 'pie' ;
  6 , 'name' , 'ex' ;
  7 , 'name' , 'a' ;
  8 , 'name' , 'g' ;
  9 , 'name' , 'u' ;
  10 , 'name' , 'v' ;
  11 , 'name' , 'e' ;
};
M_.mapping.y.eqidx = [1 3 4 5 ];
M_.mapping.ii.eqidx = [1 3 ];
M_.mapping.rn.eqidx = [1 2 ];
M_.mapping.pie.eqidx = [3 4 5 6 ];
M_.mapping.a.eqidx = [2 7 ];
M_.mapping.g.eqidx = [1 8 ];
M_.mapping.u.eqidx = [5 9 ];
M_.mapping.v.eqidx = [3 10 ];
M_.mapping.e.eqidx = [6 11 ];
M_.mapping.ex.eqidx = [1 6 ];
M_.mapping.m.eqidx = [3 4 ];
M_.mapping.eps_a.eqidx = [7 ];
M_.mapping.eps_g.eqidx = [8 ];
M_.mapping.eps_u.eqidx = [9 ];
M_.mapping.eps_v.eqidx = [10 ];
M_.mapping.eps_e.eqidx = [11 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.block_structure.time_recursive = false;
M_.block_structure.block(1).Simulation_Type = 1;
M_.block_structure.block(1).endo_nbr = 5;
M_.block_structure.block(1).mfs = 5;
M_.block_structure.block(1).equation = [ 7 8 9 10 11];
M_.block_structure.block(1).variable = [ 5 6 7 8 9];
M_.block_structure.block(1).is_linear = true;
M_.block_structure.block(1).NNZDerivatives = 10;
M_.block_structure.block(1).bytecode_jacob_cols_to_sparse = [1 2 3 4 5 6 7 8 9 10 ];
M_.block_structure.block(2).Simulation_Type = 1;
M_.block_structure.block(2).endo_nbr = 1;
M_.block_structure.block(2).mfs = 1;
M_.block_structure.block(2).equation = [ 2];
M_.block_structure.block(2).variable = [ 3];
M_.block_structure.block(2).is_linear = true;
M_.block_structure.block(2).NNZDerivatives = 1;
M_.block_structure.block(2).bytecode_jacob_cols_to_sparse = [2 ];
M_.block_structure.block(3).Simulation_Type = 8;
M_.block_structure.block(3).endo_nbr = 9;
M_.block_structure.block(3).mfs = 8;
M_.block_structure.block(3).equation = [ 3 6 4 12 13 14 15 1 5];
M_.block_structure.block(3).variable = [ 2 10 11 12 13 14 15 1 4];
M_.block_structure.block(3).is_linear = true;
M_.block_structure.block(3).NNZDerivatives = 23;
M_.block_structure.block(3).bytecode_jacob_cols_to_sparse = [3 4 5 6 7 8 0 9 10 11 12 13 14 15 16 23 24 ];
M_.block_structure.block(1).g1_sparse_rowval = int32([]);
M_.block_structure.block(1).g1_sparse_colval = int32([]);
M_.block_structure.block(1).g1_sparse_colptr = int32([]);
M_.block_structure.block(2).g1_sparse_rowval = int32([]);
M_.block_structure.block(2).g1_sparse_colval = int32([]);
M_.block_structure.block(2).g1_sparse_colptr = int32([]);
M_.block_structure.block(3).g1_sparse_rowval = int32([4 2 6 2 5 1 3 1 7 2 7 3 4 5 6 7 8 7 8 7 1 8 ]);
M_.block_structure.block(3).g1_sparse_colval = int32([3 4 5 6 7 8 8 9 9 10 10 11 12 13 14 15 15 16 16 23 24 24 ]);
M_.block_structure.block(3).g1_sparse_colptr = int32([1 1 1 2 3 4 5 6 8 10 12 13 14 15 16 18 20 20 20 20 20 20 20 21 23 ]);
M_.block_structure.variable_reordered = [ 5 6 7 8 9 3 2 10 11 12 13 14 15 1 4];
M_.block_structure.equation_reordered = [ 7 8 9 10 11 2 3 6 4 12 13 14 15 1 5];
M_.block_structure.incidence(1).lead_lag = -1;
M_.block_structure.incidence(1).sparse_IM = [
 4 13;
 4 15;
 6 4;
 7 5;
 8 6;
 9 7;
 10 8;
 11 9;
 12 4;
 13 12;
 14 1;
 15 14;
];
M_.block_structure.incidence(2).lead_lag = 0;
M_.block_structure.incidence(2).sparse_IM = [
 1 1;
 1 2;
 1 3;
 1 6;
 1 10;
 2 3;
 2 5;
 3 1;
 3 2;
 3 4;
 3 8;
 3 11;
 4 11;
 5 1;
 5 4;
 5 7;
 6 9;
 6 10;
 7 5;
 8 6;
 9 7;
 10 8;
 11 9;
 12 12;
 13 13;
 14 14;
 15 15;
];
M_.block_structure.incidence(3).lead_lag = 1;
M_.block_structure.incidence(3).sparse_IM = [
 1 1;
 2 5;
 5 4;
 6 4;
];
M_.block_structure.dyn_tmp_nbr = 0;
M_.state_var = [5 6 7 8 9 12 13 14 15 1 4 ];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(15, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(23, 1);
M_.endo_trends = struct('deflator', cell(15, 1), 'log_deflator', cell(15, 1), 'growth_factor', cell(15, 1), 'log_growth_factor', cell(15, 1));
M_.NNZDerivatives = [48; 0; -1; ];
M_.dynamic_g1_sparse_rowval = int32([14 6 12 7 8 9 10 11 13 4 15 4 1 3 5 1 3 1 2 3 5 2 7 1 8 5 9 3 10 6 11 1 6 3 4 12 13 14 15 1 5 6 2 7 8 9 10 11 ]);
M_.dynamic_g1_sparse_colval = int32([1 4 4 5 6 7 8 9 12 13 14 15 16 16 16 17 17 18 18 19 19 20 20 21 21 22 22 23 23 24 24 25 25 26 26 27 28 29 30 31 34 34 35 46 47 48 49 50 ]);
M_.dynamic_g1_sparse_colptr = int32([1 2 2 2 4 5 6 7 8 9 9 9 10 11 12 13 16 18 20 22 24 26 28 30 32 34 36 37 38 39 40 41 41 41 43 44 44 44 44 44 44 44 44 44 44 44 45 46 47 48 49 ]);
M_.dynamic_g2_sparse_indices = int32([]);
M_.lhs = {
'y'; 
'rn'; 
'ii'; 
'm'; 
'pie'; 
'ex'; 
'a'; 
'g'; 
'u'; 
'v'; 
'e'; 
'AUX_ENDO_LAG_3_1'; 
'AUX_ENDO_LAG_3_2'; 
'AUX_ENDO_LAG_0_1'; 
'AUX_ENDO_LAG_0_2'; 
};
M_.static_tmp_nbr = [0; 0; 0; 0; ];
M_.block_structure_stat.block(1).Simulation_Type = 1;
M_.block_structure_stat.block(1).endo_nbr = 1;
M_.block_structure_stat.block(1).mfs = 1;
M_.block_structure_stat.block(1).equation = [ 2];
M_.block_structure_stat.block(1).variable = [ 3];
M_.block_structure_stat.block(2).Simulation_Type = 3;
M_.block_structure_stat.block(2).endo_nbr = 1;
M_.block_structure_stat.block(2).mfs = 1;
M_.block_structure_stat.block(2).equation = [ 7];
M_.block_structure_stat.block(2).variable = [ 5];
M_.block_structure_stat.block(3).Simulation_Type = 3;
M_.block_structure_stat.block(3).endo_nbr = 1;
M_.block_structure_stat.block(3).mfs = 1;
M_.block_structure_stat.block(3).equation = [ 8];
M_.block_structure_stat.block(3).variable = [ 6];
M_.block_structure_stat.block(4).Simulation_Type = 3;
M_.block_structure_stat.block(4).endo_nbr = 1;
M_.block_structure_stat.block(4).mfs = 1;
M_.block_structure_stat.block(4).equation = [ 9];
M_.block_structure_stat.block(4).variable = [ 7];
M_.block_structure_stat.block(5).Simulation_Type = 3;
M_.block_structure_stat.block(5).endo_nbr = 1;
M_.block_structure_stat.block(5).mfs = 1;
M_.block_structure_stat.block(5).equation = [ 10];
M_.block_structure_stat.block(5).variable = [ 8];
M_.block_structure_stat.block(6).Simulation_Type = 3;
M_.block_structure_stat.block(6).endo_nbr = 1;
M_.block_structure_stat.block(6).mfs = 1;
M_.block_structure_stat.block(6).equation = [ 11];
M_.block_structure_stat.block(6).variable = [ 9];
M_.block_structure_stat.block(7).Simulation_Type = 6;
M_.block_structure_stat.block(7).endo_nbr = 9;
M_.block_structure_stat.block(7).mfs = 9;
M_.block_structure_stat.block(7).equation = [ 1 3 4 5 6 12 13 14 15];
M_.block_structure_stat.block(7).variable = [ 2 4 11 1 10 12 13 14 15];
M_.block_structure_stat.variable_reordered = [ 3 5 6 7 8 9 2 4 11 1 10 12 13 14 15];
M_.block_structure_stat.equation_reordered = [ 2 7 8 9 10 11 1 3 4 5 6 12 13 14 15];
M_.block_structure_stat.incidence.sparse_IM = [
 1 2;
 1 3;
 1 6;
 1 10;
 2 3;
 3 1;
 3 2;
 3 4;
 3 8;
 3 11;
 4 11;
 4 13;
 4 15;
 5 1;
 5 4;
 5 7;
 6 4;
 6 9;
 6 10;
 7 5;
 8 6;
 9 7;
 10 8;
 11 9;
 12 4;
 12 12;
 13 12;
 13 13;
 14 1;
 14 14;
 15 14;
 15 15;
];
M_.block_structure_stat.tmp_nbr = 0;
M_.block_structure_stat.block(1).g1_sparse_rowval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colval = int32([]);
M_.block_structure_stat.block(1).g1_sparse_colptr = int32([]);
M_.block_structure_stat.block(2).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(2).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(3).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(3).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(4).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(4).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(5).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(5).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(6).g1_sparse_rowval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colval = int32([1 ]);
M_.block_structure_stat.block(6).g1_sparse_colptr = int32([1 2 ]);
M_.block_structure_stat.block(7).g1_sparse_rowval = int32([1 2 2 4 5 6 2 3 2 4 8 1 5 6 7 3 7 8 9 3 9 ]);
M_.block_structure_stat.block(7).g1_sparse_colval = int32([1 1 2 2 2 2 3 3 4 4 4 5 5 6 6 7 7 8 8 9 9 ]);
M_.block_structure_stat.block(7).g1_sparse_colptr = int32([1 3 7 9 12 14 16 18 20 22 ]);
M_.static_g1_sparse_rowval = int32([3 5 14 1 3 1 2 3 5 6 12 7 1 8 5 9 3 10 6 11 1 6 3 4 12 13 4 13 14 15 4 15 ]);
M_.static_g1_sparse_colval = int32([1 1 1 2 2 3 3 4 4 4 4 5 6 6 7 7 8 8 9 9 10 10 11 11 12 12 13 13 14 14 15 15 ]);
M_.static_g1_sparse_colptr = int32([1 4 6 8 12 13 15 17 19 21 23 25 27 29 31 33 ]);
M_.params(1) = 0.97;
beta = M_.params(1);
M_.params(2) = 2.5;
sigma = M_.params(2);
M_.params(11) = 1/M_.params(1)-1;
rho = M_.params(11);
M_.params(22) = 1.5;
phi_pie = M_.params(22);
M_.params(23) = 0.5;
phi_y = M_.params(23);
M_.params(3) = 1;
phi = M_.params(3);
M_.params(6) = 0.3333333333333333;
alpha = M_.params(6);
M_.params(4) = 11;
epsilon = M_.params(4);
M_.params(5) = 0.6666666666666666;
theta = M_.params(5);
M_.params(7) = (1+M_.params(3))/(M_.params(6)+M_.params(3)+M_.params(2)*(1-M_.params(6)));
PSI_yan = M_.params(7);
M_.params(8) = (1-M_.params(6))/(1-M_.params(6)+M_.params(6)*M_.params(4));
THETA = M_.params(8);
M_.params(9) = (1-M_.params(5))*(1-M_.params(1)*M_.params(5))*M_.params(8)/M_.params(5);
lambda = M_.params(9);
M_.params(10) = M_.params(9)*(M_.params(2)+(M_.params(3)+M_.params(6))/(1-M_.params(6)));
kappa = M_.params(10);
M_.params(12) = 0.9;
rho_a = M_.params(12);
M_.params(13) = 0.9;
rho_g = M_.params(13);
M_.params(14) = 0.8;
rho_u = M_.params(14);
M_.params(15) = 0.7;
rho_v = M_.params(15);
M_.params(16) = 0.9;
rho_e = M_.params(16);
M_.params(17) = 0.5;
rho_m = M_.params(17);
M_.params(18) = 0.7;
OMEGA = M_.params(18);
M_.params(20) = 0.7;
MU = M_.params(20);
M_.params(19) = 0.7;
TAU = M_.params(19);
M_.params(21) = 0;
IOTA = M_.params(21);
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 0;
M_.Sigma_e(3, 3) = 0;
M_.Sigma_e(4, 4) = 1;
M_.Sigma_e(5, 5) = 1;
options_.irf = 12;
options_.order = 2;
options_.periods = 1000;
var_list_ = {};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'oo_recursive_', '-append');
end
if exist('options_mom_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'EC424_NKD_developing_results.mat'], 'options_mom_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
